import pandas as pd

mapping_data = {
  "US": {"region": "North America", "continent": "Americas"},
  "ES": {"region": "Southern Europe", "continent": "Europe"},
  "KR": {"region": "Eastern Asia", "continent": "Asia"},
  "GB": {"region": "Northern Europe", "continent": "Europe"},
  "JP": {"region": "Eastern Asia", "continent": "Asia"},
  "CA": {"region": "North America", "continent": "Americas"},
  "DE": {"region": "Western Europe", "continent": "Europe"},
  "MX": {"region": "Central America", "continent": "Americas"},
  "FR": {"region": "Western Europe", "continent": "Europe"},
  "CO": {"region": "South America", "continent": "Americas"},
  "TR": {"region": "Western Asia", "continent": "Asia"},
  "AR": {"region": "South America", "continent": "Americas"},
  "BR": {"region": "South America", "continent": "Americas"},
  "DK": {"region": "Northern Europe", "continent": "Europe"},
  "IE": {"region": "Northern Europe", "continent": "Europe"},
  "SE": {"region": "Northern Europe", "continent": "Europe"},
  "NO": {"region": "Northern Europe", "continent": "Europe"},
  "TH": {"region": "Southeast Asia", "continent": "Asia"},
  "IT": {"region": "Southern Europe", "continent": "Europe"},
  "CN": {"region": "Eastern Asia", "continent": "Asia"},
  "CL": {"region": "South America", "continent": "Americas"},
  "AU": {"region": "Australia and New Zealand", "continent": "Oceania"},
  "JO": {"region": "Western Asia", "continent": "Asia"},
  "VE": {"region": "South America", "continent": "Americas"},
  "BE": {"region": "Western Europe", "continent": "Europe"},
  "RU": {"region": "Eastern Europe", "continent": "Europe"},
  "PR": {"region": "Caribbean", "continent": "Americas"},
  "JM": {"region": "Caribbean", "continent": "Americas"},
  "NZ": {"region": "Australia and New Zealand", "continent": "Oceania"},
  "ZA": {"region": "Southern Africa", "continent": "Africa"},
  "IS": {"region": "Northern Europe", "continent": "Europe"},
  "PH": {"region": "Southeast Asia", "continent": "Asia"},
  "AT": {"region": "Western Europe", "continent": "Europe"},
  "IL": {"region": "Western Asia", "continent": "Asia"},
  "SI": {"region": "Southern Europe", "continent": "Europe"},
  "PL": {"region": "Eastern Europe", "continent": "Europe"},
  "PE": {"region": "South America", "continent": "Americas"},
  "IN": {"region": "Southern Asia", "continent": "Asia"},
  "EG": {"region": "Northern Africa", "continent": "Africa"},
  "NG": {"region": "Western Africa", "continent": "Africa"},
  "CH": {"region": "Western Europe", "continent": "Europe"},
  "FI": {"region": "Northern Europe", "continent": "Europe"},
  "SU": {"region": "Eastern Europe", "continent": "Europe"},
  "TW": {"region": "Eastern Asia", "continent": "Asia"},
  "LU": {"region": "Western Europe", "continent": "Europe"},
  "NL": {"region": "Western Europe", "continent": "Europe"},
  "EC": {"region": "South America", "continent": "Americas"},
  "UA": {"region": "Eastern Europe", "continent": "Europe"},
  "HU": {"region": "Eastern Europe", "continent": "Europe"},
  "XC": {"region": "Middle East", "continent": "Asia"},
  "IQ": {"region": "Western Asia", "continent": "Asia"},
  "PT": {"region": "Southern Europe", "continent": "Europe"},
  "SG": {"region": "Southeast Asia", "continent": "Asia"},
  "RO": {"region": "Eastern Europe", "continent": "Europe"},
  "CZ": {"region": "Eastern Europe", "continent": "Europe"},
  "BG": {"region": "Eastern Europe", "continent": "Europe"},
  "AE": {"region": "Middle East", "continent": "Asia"},
  "HK": {"region": "Eastern Asia", "continent": "Asia"},
  "GR": {"region": "Southern Europe", "continent": "Europe"},
  "UY": {"region": "South America", "continent": "Americas"},
  "QA": {"region": "Middle East", "continent": "Asia"},
  "VN": {"region": "Southeast Asia", "continent": "Asia"},
  "KE": {"region": "Eastern Africa", "continent": "Africa"},
  "RS": {"region": "Southern Europe", "continent": "Europe"},
  "HR": {"region": "Southern Europe", "continent": "Europe"},
  "IR": {"region": "Middle East", "continent": "Asia"},
  "XG": {"region": "Middle East", "continent": "Asia"},
  "BD": {"region": "Southern Asia", "continent": "Asia"},
  "LB": {"region": "Middle East", "continent": "Asia"},
  "BO": {"region": "South America", "continent": "Americas"},
  "ID": {"region": "Southeast Asia", "continent": "Asia"},
  "IO": {"region": "Eastern Africa", "continent": "Africa"},
  "PK": {"region": "Southern Asia", "continent": "Asia"},
  "MY": {"region": "Southeast Asia", "continent": "Asia"},
  "CU": {"region": "Caribbean", "continent": "Americas"},
  "KW": {"region": "Middle East", "continent": "Asia"},
  "SA": {"region": "Middle East", "continent": "Asia"},
  "TO": {"region": "Polynesia", "continent": "Oceania"},
  "SK": {"region": "Eastern Europe", "continent": "Europe"},
  "SY": {"region": "Middle East", "continent": "Asia"},
  "KZ": {"region": "Central Asia", "continent": "Asia"},
  "KP": {"region": "Eastern Asia", "continent": "Asia"},
  "YU": {"region": "Southern Europe", "continent": "Europe"},
  "BA": {"region": "Southern Europe", "continent": "Europe"},
  "MA": {"region": "Northern Africa", "continent": "Africa"},
  "EE": {"region": "Northern Europe", "continent": "Europe"},
  "LK": {"region": "Southern Asia", "continent": "Asia"},
  "TN": {"region": "Northern Africa", "continent": "Africa"},
  "GE": {"region": "Western Asia", "continent": "Asia"},
  "DO": {"region": "Caribbean", "continent": "Americas"},
  "SN": {"region": "Western Africa", "continent": "Africa"},
  "TZ": {"region": "Eastern Africa", "continent": "Africa"},
  "AL": {"region": "Southern Europe", "continent": "Europe"},
  "AZ": {"region": "Western Asia", "continent": "Asia"},
  "MV": {"region": "Southern Asia", "continent": "Asia"},
  "XK": {"region": "Southern Europe", "continent": "Europe"},
  "CS": {"region": "Southern Europe", "continent": "Europe"},
  "CY": {"region": "Southern Europe", "continent": "Europe"},
  "LV": {"region": "Northern Europe", "continent": "Europe"},
  "AM": {"region": "Western Asia", "continent": "Asia"},
  "AF": {"region": "Southern Asia", "continent": "Asia"},
  "UG": {"region": "Eastern Africa", "continent": "Africa"},
  "BW": {"region": "Southern Africa", "continent": "Africa"},
  "CM": {"region": "Middle Africa", "continent": "Africa"},
  "MD": {"region": "Eastern Europe", "continent": "Europe"},
  "PG": {"region": "Melanesia", "continent": "Oceania"},
  "DZ": {"region": "Northern Africa", "continent": "Africa"},
  "LT": {"region": "Northern Europe", "continent": "Europe"},
  "BH": {"region": "Middle East", "continent": "Asia"},
  "BY": {"region": "Eastern Europe", "continent": "Europe"},
  "YE": {"region": "Middle East", "continent": "Asia"},
  "BU": {"region": "Southeast Asia", "continent": "Asia"},
  "SO": {"region": "Eastern Africa", "continent": "Africa"},
  "NI": {"region": "Central America", "continent": "Americas"},
  "CR": {"region": "Central America", "continent": "Americas"},
  "TG": {"region": "Western Africa", "continent": "Africa"},
  "ZW": {"region": "Eastern Africa", "continent": "Africa"},
  "PY": {"region": "South America", "continent": "Americas"},
  "MT": {"region": "Southern Europe", "continent": "Europe"},
  "NP": {"region": "Southern Asia", "continent": "Asia"},
  "PS": {"region": "Middle East", "continent": "Asia"},
  "MN": {"region": "Eastern Asia", "continent": "Asia"},
  "KH": {"region": "Southeast Asia", "continent": "Asia"},
  "HN": {"region": "Central America", "continent": "Americas"},
  "BN": {"region": "Southeast Asia", "continent": "Asia"},
  "ZM": {"region": "Eastern Africa", "continent": "Africa"},
  "XI": {"region": "Middle East", "continent": "Asia"},
  "MK": {"region": "Southern Europe", "continent": "Europe"},
  "CI": {"region": "Western Africa", "continent": "Africa"},
  "AO": {"region": "Middle Africa", "continent": "Africa"},
  "MM": {"region": "Southeast Asia", "continent": "Asia"},
  "BZ": {"region": "Central America", "continent": "Americas"},
  "SZ": {"region": "Southern Africa", "continent": "Africa"},
  "FJ": {"region": "Melanesia", "continent": "Oceania"},
  "AW": {"region": "Caribbean", "continent": "Americas"},
  "GA": {"region": "Middle Africa", "continent": "Africa"},
  "ET": {"region": "Eastern Africa", "continent": "Africa"},
  "LY": {"region": "Northern Africa", "continent": "Africa"},
  "TT": {"region": "Caribbean", "continent": "Americas"},
  "AN": {"region": "Caribbean", "continent": "Americas"},
  "GH": {"region": "Western Africa", "continent": "Africa"},
  "ME": {"region": "Southern Europe", "continent": "Europe"},
  "PA": {"region": "Central America", "continent": "Americas"},
  "BF": {"region": "Western Africa", "continent": "Africa"},
  "CD": {"region": "Middle Africa", "continent": "Africa"},
  "LA": {"region": "Southeast Asia", "continent": "Asia"},
  "ST": {"region": "Middle Africa", "continent": "Africa"},
  "MP": {"region": "Micronesia", "continent": "Oceania"},
  "ML": {"region": "Western Africa", "continent": "Africa"},
  "AD": {"region": "Southern Europe", "continent": "Europe"},
  "VU": {"region": "Melanesia", "continent": "Oceania"},
  "NC": {"region": "Melanesia", "continent": "Oceania"},
  "BS": {"region": "Caribbean", "continent": "Americas"},
  "CF": {"region": "Middle Africa", "continent": "Africa"}
}


data = pd.read_csv(r'C:\Users\JOLO\Desktop\newcleaned.csv', low_memory=False)

show_dim_table = data[['show_name', 'show_type', 'show_status', 'in_production', 'availableTranslations', 'origin_country']].copy()
show_dim_table['origin_Region'] = ''
show_dim_table['origin_Continent'] = ''

show_dim_table['origin_Region'] = show_dim_table['origin_country'].map(lambda x: mapping_data.get(x, {}).get('region', ''))
show_dim_table['origin_Continent'] = show_dim_table['origin_country'].map(lambda x: mapping_data.get(x, {}).get('continent', ''))

show_dim_table['show_id'] = range(5000, 5000 + len(show_dim_table))
cols = show_dim_table.columns.tolist()
cols = ['show_id'] + [col for col in cols if col != 'show_id']
show_dim_table = show_dim_table[cols]

show_dim_table.to_csv(r'C:\Users\JOLO\Desktop\Dim_Show.txt', sep=',', index=False)

